### ISSUE TITLE
Version 0.8.0 on PyPI is not the same as the GitHub Version 0.8.0

### ISSUE THREAD

**Issue by rmcgregor1990** [NordicSemiconductor/pc-ble-driver-py#13]
The version on PyPI does not have read request support in BLEDriver & BLEAdapter while the version in this repo does. Both claim to be version 0.8.0.

**Comment by bihanssen** [comment]
Hi, the version number in master branch has not been modified after the release to pip, so they would both show up as 0.8.0. I've added a tag v0.8.0 to show what commit corresponds to the pip 0.8.0 release.
