### ISSUE TITLE
Support read/write to multiple attributes with Shared UUIDs

### ISSUE THREAD

**Issue by labishrestha2** [NordicSemiconductor/pc-ble-driver-py#132]
I looked around in the forums, but couldn't find anything related to this issue. 
According to Core 4.0 spec, A service may have multiple characteristic definitions with the same Characteristic UUID (pdf page 1897/2302, Bluetooth 4, Core specification, page 537)
https://www.bluetooth.org/docman/handlers/downloaddoc.ashx?doc_id=229737

In our application, we have two attributes that share the same 16b UUID under different services. Please correct me If I'm wrong, but I Can't seem to find a way in pc-ble-driver-py 0.13.0 to read or write to both the attributes individually.

One way to fix this may be to add a handle based read/write functions. I'll try this method and submit a PR if that works.

**Comment by bihanssen** [comment]
Fixed in PR 174
