### ISSUE TITLE
pc-ble-driver-py 0.14.2 not support mingw64?

### ISSUE THREAD

**Issue by shaoyuan1943** [NordicSemiconductor/pc-ble-driver-py#164]

**Comment by bihanssen** [comment]
@shaoyuan1943 , pc-ble-driver-py does not support mingw64. There are no immediate plans to support that.

**Comment by shaoyuan1943** [comment]
@bihanssen OK，thanks.

**Comment by elfmimi** [comment]
Could you make this mentioned in README.md ?
