### ISSUE TITLE
Support of Python 3.10

### ISSUE THREAD

**Issue by sebastianpfischer** [NordicSemiconductor/pc-ble-driver-py#217]
Hi,

What is the plan to support python 3.10 for pc-ble-driver.py?

The new ubuntu release 22.04LTS is using python 3.10 as default python version which means, anybody upgrading to it, will not be able to use the driver.

Thank you in advance

**Comment by katjie** [comment]
They have updated the version on github now, but it seems it has not been uploaded to PyPi yet

**Comment by sebastianpfischer** [comment]
Yes, I saw that. I think their release process stops when it ends up on Pypi. They are probably testing it internally. I just really hope that it does not take 2 more weeks 🤞
