### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by samstagern** [NordicSemiconductor/pc-ble-driver-py#27]
Dear NordicSemiconductor,

Thanks for creating the python ble driver! Is a version for python 3 already planned? Is there already work done on Python 3 and are there known difficulties in porting?

Greetings,
Samstagern

**Comment by n6hpa** [comment]
Please please implement this!  I really don't want to have to do this myself

**Comment by samstagern** [comment]
Before I start porting
- are there any known issues in advance?

Looking through the code it seems reasonably simple to port it, so that it supports both 2.7 and 3.

**Comment by samstagern** [comment]
There seems to be already ongoing effort at jorgenmk/pc-ble-driver-py. Do you have contact with that developer?

**Comment by samstagern** [comment]
I have a draft version for preview here: https://github.com/samstagern/pc-ble-driver-py.git

**Comment by bihanssen** [comment]
Hi @samstagern, sorry for the late reply, and thanks for sharing your code.
Our policy has been that since we have internal teams requiring python2, we haven't started adding python3 support. See [nrfutil comment](https://github.com/NordicSemiconductor/pc-nrfutil/issues/40#issuecomment-332166173).

However, as you have already discovered, @jorgenmk has also been looking into creating py3 version of pc-ble-driver-py. The job with adding py3 support seems to be relatively small. 
Before potentially releasing this we would need to find a good solution for how to make both versions available in pip.

**Comment by LJBD** [comment]
@bihanssen AFAIK to make both versions available in `pip`, you can upload wheels for multiple Python versions (see [this](https://packaging.python.org/tutorials/distributing-packages/#wheels)). A good, although a bit extreme example of that would be [PyMongo](https://pypi.python.org/pypi/pymongo) which has a ton of wheels built for each version of the package itself.

I'd recommend setting up a Travis job that would build the wheels for Python 2.7 and 3.x.

**Comment by samstagern** [comment]
@LJBD  that seems indeed a good way to go. In the fork I did the code is both python 2 and 3 compatible at source level. It is a bit more effort, but I think it makes sense to keep a single source for this package. If someone can help review and test the fork I will create a pull request.

**Comment by nowox** [comment]
#117

**Comment by yoonlee95** [comment]
Hello,
I am also interested in getting pc-ble-driver to work on python3.

If anybody was successful, Can I get some pointers on how to do so?

**Comment by tjstone14** [comment]
This library is great, but it is getting to be difficult to support python 2 as other libraries are dropping support.  I see there is a pull request for python 3 that hasn't yet been merged.  Is the plan to merge in the pull request or is there some other activity in the works for python 3?

**Comment by bihanssen** [comment]
There is still a desire to from Nordic to get support for Python 3 in pc-ble-driver-py. The challenge with the current PR (py3 SD API v5) is that is pulls in many changes at once, and the work of reviewing and completing that job has not been prioritized. 

It could be that by focusing on the changes required for Python 3 (that is 2 + 3), and not pulling in SD API-upgrade, it would be easier to get the changes merged. 

Python 2+3 support would have to include not just py source code changes, but also a solution for building and bundling binaries (swig compilation) for both py 2 and 3.
If someone would do a PR on this (py 2+3), it would most likely speed things up.

**Comment by dalgr** [comment]
@bihanssen 
please review
https://github.com/NordicSemiconductor/pc-ble-driver-py/pull/50

**Comment by cooperlees** [comment]
Hi,

What's my best way to run the current test suite?

I've prepared a diff to plumb up the current unit tests to setup.py but I want to ensure Python 2 all passes before I start making changes for Python 2/3 support. Diff:
https://github.com/cooperlees/pc-ble-driver-py/commit/15c50a052959395bf52916ab73e81d2f63f7c444

I've been trying after creating a 2.7.15 virtualenv:
```
/tmp/test_ble_py2/bin/python setup.py test
```

I get `RuntimeError: Connectivity IC identifier __conn_ic_id__ is not set` - Full Output: https://pastebin.com/Nx7wQCHs

If we could get a little tutorial on how to test today, I'll try make the unit tests more self contained so they should just run when you have a virtualenv with all the dependencies installed.

**Comment by bihanssen** [comment]
For reference: A new release of pc-ble-driver-py with python 3 support is currently in development (currently branch feature/sd132v5_py3).
@cooperlees, sorry for late response. If you are still having issues or need assistance please report in a separate ticket.

**Comment by bihanssen** [comment]
@martijnthe, thanks for your interest. No ETA, but the release is progressing well and will be out soon.

**Comment by goldwake** [comment]
This can be closed. [v0.12.0 supports python 3](https://github.com/NordicSemiconductor/pc-ble-driver-py/releases/tag/0.12.0)

**Comment by bihanssen** [comment]
@goldwake thanks for the reminder. Closing this issue.
