### ISSUE TITLE
BLEAdapter not exposing BLE features

### ISSUE THREAD

**Issue by Darrew** [NordicSemiconductor/pc-ble-driver-py#46]
Under many other things, class BLEAdapter does not support neither Bonding nor encryption. 
(Note that method authenticate in ble_adapter calls driver.ble_gap_authenticate with sec_params.bond set to False)

This may be consider not to be an issue. But, the usability of this repo is rather conditioned to the fact that many ble features are not exposed on the adapter. @Administrators Pls consider to extend the class BLEAdapter or take into account external Pull requests.

**Comment by bihanssen** [comment]
Closing this issue as covered by PR #47.
