### ISSUE TITLE
No answer from nordic chip

### ISSUE THREAD

**Issue by mohamed-elsabagh** [NordicSemiconductor/pc-ble-driver-py#49]
I flashed Nordic soft device [connectivity_2.0.1_115k2_with_s132_5.0.hex](https://github.com/NordicSemiconductor/pc-ble-driver/blob/master/hex/sd_api_v5/connectivity_2.0.1_115k2_with_s132_5.0.hex) into my NRF52 and I am trying to connect from my Ubuntu using Boost ver 1.63
When I run advertiser example code I can see on my logic analyzer that my Ubuntu machine is trying to send characters with baudrate 1152K but I never get response from my NRF52 I am not sure what's going on wrong here
![schermata 2018-02-22 alle 13 40 30](https://user-images.githubusercontent.com/10185468/36556233-2dd81abc-180d-11e8-9fa6-a1b9e0da7525.png)

**Comment by rmcgregor1990** [comment]
That firmware uses a 1M baudrate, as the 1m in the name signifies.

**Comment by mohamed-elsabagh** [comment]
sorry I miss typed the wrong firmware version, I am using the 1152K firmware and I am facing the mentioned behavior

**Comment by chunfantasy** [comment]
Hi @mohamed-elsabagh , the firmware  `connectivity_2.0.1_115k2_with_s132_5.0.hex` you are using is for v5. But for the current pc-ble-driver-py is only supporting v2 and v3 now.

**Comment by mohamed-elsabagh** [comment]
I apologize I used this http://www.nordicsemi.com/eng/Products/Bluetooth-low-energy/nRF52832 firmware, v3 and v2 and I still have the same problem

**Comment by bencefr** [comment]
In the code tree `pc-ble-driver/hex/`[sd_api_v3](https://github.com/NordicSemiconductor/pc-ble-driver/tree/99b5e78f96de60ee70e749bb89b280116275fb97/hex/sd_api_v3).

**Comment by mohamed-elsabagh** [comment]
I used the mentioned firmware, but still getting the same behavior, is there a special hardware connection I should connect my nordic chip so that it can work, I am just connecting TX ,RX, DTR, CTS between nrf52 dvk and my usb2uart, is there a special pin or port should be connected to a certain level?

**Comment by bihanssen** [comment]
Hi, to clarify, you have linked to documentation of two different serialization transports, Raw and HCI. Raw transport uses a two byte header, though HCI transport uses SLIP (0xC0) and a four byte header. There is no length field in HCI transport, instead SLIP is used to tell when a packets starts and ends.
pc-ble-driver uses HCI transport. 

To answer your previous question, it is correct that you need TX, RX, DTR and CTS. No other lines are needed. It is however crucial that the flow control operates correctly, or you'll quickly end up with lost bytes. Getting the hw flow control correct is often the biggest challenge when using other serial2usb converters.

**Comment by mohamed-elsabagh** [comment]
so the packets sent over UART are correct, so I can't figure out where is the problem, I tried connecting CTS and RTS to ground and still can't get any response from the board, I am using BT832X from fantsel

**Comment by bihanssen** [comment]
I'm not sure why things are failing with your setup. Supporting custom board setups are somewhat outside the scope of this issue tracker. I advice you to ask about your issue on devzone in addition. Also, it could be worthwhile to get pc-ble-driver running with a nordic devkit and observing how a working uart communication operates.

**Comment by mohamed-elsabagh** [comment]
I lowered the optimization level on keil, flashed the firmware and run the C examples and I can now see some response from the nrf52 board, thanks

**Comment by bihanssen** [comment]
That's good to hear. Thanks for the update.
