### ISSUE TITLE
Support to latest soft device

### ISSUE THREAD

**Issue by mohamed-elsabagh** [NordicSemiconductor/pc-ble-driver-py#53]
Hello, is there any plan about when the python binding version can support latest sdk and latest softdevice version?

**Comment by bihanssen** [comment]
Hi,
the roadmap for sdk 15 (SD v6) support is first pc-ble-driver, then pc-ble-driver-js, and after that pc-ble-driver-py. It will take some time before -py support is in place is all I can say I'm afraid, no release time has been scheduled.

**Comment by bihanssen** [comment]
Closing as duplicated by #68
