### ISSUE TITLE
how to setup pc-ble-driver-py on anaconda 

### ISSUE THREAD

**Issue by amigomcu** [NordicSemiconductor/pc-ble-driver-py#60]
hi all, 
i get PyThreadState_Get: no current thread error , 

python advertising.py NRF52 /dev/tty.usbmodem1411
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6

ref link:
https://devzone.nordicsemi.com/f/nordic-q-a/15207/nrfutil-on-osx#post-id-153831

**Comment by bihanssen** [comment]
Hi,
the error usually occurs if a different python runtime is used than what the binaries were built for. We have not tested specifically against anaconda setup.
