### ISSUE TITLE
Updates for sdk 15 (SD v6)

### ISSUE THREAD

**Issue by sjb4iiii** [NordicSemiconductor/pc-ble-driver-py#68]
Any idea when python support for nRF52840 (sdk 15) will be made available?

**Comment by bihanssen** [comment]
Hi.
the current plan is to release in two stages. First a release with support for SD API v5 and python 2+3, then a release with support for SD API v6. First stage is currently in progress.

**Comment by sjb4iiii** [comment]
Is there an approximate schedule of when to expect these stages?

**Comment by marknolan** [comment]
Hi @bihanssen, 
Firstly, thank you for all your teams work, the Python bindings are really useful for development.

Is there any updated timeline for the next release? We're looking to use the newer SDKs in order to get higher data rates.

Also, it might be a noob question but, is there a reason why all the required files (i.e., the contents of the hex and lib folders) are not committed on the s132v5 branch?

**Comment by bihanssen** [comment]
@marknolan, the release will happen as soon as all issues related to py3-support are resolved. It is currently being worked on.

**Comment by marknolan** [comment]
@bihanssen , I'm just following up on this, is there any estimated release date? I really appreciate all the work your team are doing it's just some of our team are relying on this project and issues with the older version do slow down our work flow a good bit.

**Comment by bihanssen** [comment]
@marknolan, thanks for your interest. No ETA, but the release is progressing well and will be out soon.

**Comment by bihanssen** [comment]
Hi,
some information regarding SoftDevice support. 
We (maintainers of ble-driver-py) have no current plans to add support for SoftDevice v6. The reason for this is that SoftDevice v6 has some API changes to scanning and advertising that would either reduce the scanning performance for ble-driver, or require added custom logic and complexity in the connectivity firmware. We think that the features available in SoftDevice v5 are adequate for the time being, so we will not be adding support for v6 any time soon.
Note that ble-driver (C++) does have support for SD v6, so this applies to ble-driver-py (and -js) only.
