### ISSUE TITLE
How to get the Heart rate monitor example started ?

### ISSUE THREAD

**Issue by anujdutt9** [NordicSemiconductor/pc-ble-driver-py#7]
Hi, I have installed the driver using pip and ran the hear rate monitor code. It says: "Enter your choice" . What is it asking for as input ? can you please help
Thanks : )

**Comment by carlescufi** [comment]
have you connected an nRF51 o nRF52 devkit board to your computer?

**Comment by anujdutt9** [comment]
Yes. I have the nRF51 board connected to my laptop.

**Comment by carlescufi** [comment]
Can you paste here the output of:
`nrfjprog -i`

**Comment by carlescufi** [comment]
Remember in any case that you can provide the serial port as a parameter to any of the examples:

`python <example>.py <SERIAL_PORT>`

Where `SERIAL_PORT` is `COMXX` or `dev/ttyACMxx`

**Comment by anujdutt9** [comment]
ok. I'll try this today, Thanks for the help : )
