### ISSUE TITLE
Cmake build error

### ISSUE THREAD

**Issue by 0-jun** [NordicSemiconductor/pc-ble-driver-py#92]
I'm using windows 10 1803, os build : 17134.706
- cmake 3.14.2
- python3.6.5 32bit
- visual studio 2015 update 3

When i build project using python cmake(installed by requirements-dev.txt) , i got error message like below.
Because, python cmake version is 3.13.3 (https://stackoverflow.com/questions/55155941/stdout-cmake-error-no-source-or-binary-directory-provided-kivy-buildozer)

    No source or binary directory provided

When i build project using cmake 3.14.2, i got message like below.

    CMake Error at C:/vcpkg/scripts/buildsystems/vcpkg.cmake:233 (_find_package):
    By not providing "FindPythonExtensions.cmake" in CMAKE_MODULE_PATH this
    project has asked CMake to find a package configuration file provided by
    "PythonExtensions", but CMake did not find one.

    Could not find a package configuration file provided by "PythonExtensions"
    with any of the following names:

    PythonExtensionsConfig.cmake
    pythonextensions-config.cmake

And, i also install vcpkg and nrf-ble-driver pakage.

How do i build project?

**Comment by bihanssen** [comment]
Python v3 is not supported yet.
